This creates a reclassification matrix for multiple values.

clssname <- list("ctp","cop", "oop", "otp") 
oldclass <- c(1,7,8,10)                                                                                                                                                                                                                                                                                               
toclass <-c(12,17)                                                                                                                                                                                                   
namer. <- unlist(clssname)                                                                                                                                                                                                                                                                                            
year.  <-c('2003','2007', '2011', '2015', '2016', '2019')                                                                                                                                                                                                                                                               
cols <- c('from', 'to') #sets the names of the subsitute dataframe (optional)                                                                                                                                                                                                  
rec_df<-c(oldclass, oldclass) #creates dataframe. The value remains the same                                                                                                                                                                                                                                          
df <- data.frame(matrix(nrow=4, data=rec_df))                                                                                                                                                                                                                                                                           
names(df) <- cols # this is the substitution dataframe. It selects the pixels of oldclass and drops the rest. So, i only have patches of this class amnd the                                                                                                                                                               
###########################                                                                                                                                        
